# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: vedebe
google_analytics: Jeroen VdB
title: Jeroen VdB

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Jeroen Védé.Bé

description: Jeroen VdB's Blog
author:
  name: Jeroen VdB
  linkedin: jeroen-van-den-broeck-28051996
  # email: jeroen.van.den.broeck@outlook.com
  github: Jeroen-VdB
  bio: Integration Consultant at <a href="https://www.realdolmen.com/en">Realdolmen<a>.
  email_md5: 725b6309b3331481bc68a884d8cb8480

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

plugins:
  - jekyll-paginate
